In [ ]:
import numpy as np
from sklearn.preprocessing import MtandardScainMaxScaler, Sler, Normalizer

# Original data
data = np.array([[200], [300], [400], [600], [1000]])

print("Original Data:\n", data)



Original Data:
 [[ 200]
 [ 300]
 [ 400]
 [ 600]
 [1000]]


In [ ]:
# -----------------------------
# 1. Min-Max Normalization (0–1)
# -----------------------------
minmax = MinMaxScaler()
minmax_scaled = minmax.fit_transform(data)

print("\nMin-Max Normalized Data:")
print(minmax_scaled)




Min-Max Normalized Data:
[[0.   ]
 [0.125]
 [0.25 ]
 [0.5  ]
 [1.   ]]


In [ ]:
# -----------------------------
# 2. Standardization (Z-score)
# -----------------------------
standard = StandardScaler()
standard_scaled = standard.fit_transform(data)

print("\nStandardized Data (Mean=0, Std=1):")
print(standard_scaled)




Standardized Data (Mean=0, Std=1):
[[-1.06066017]
 [-0.70710678]
 [-0.35355339]
 [ 0.35355339]
 [ 1.76776695]]


In [ ]:
# -----------------------------
# 3. L2 Normalization (Unit Vector)
# -----------------------------
# Normalizer works on rows, so convert to single row
data_row = np.array([[220, 300, 400, 600, 1000]])

normalizer = Normalizer()
l2_normalized = normalizer.fit_transform(data_row)

print("\nL2 Normalized Data (Unit Vector):")
print(l2_normalized)


L2 Normalized Data (Unit Vector):
[[0.17083547 0.23295745 0.31060994 0.46591491 0.77652484]]
